### ISSUE TITLE
Subscribe users from group to the created Jira

### ISSUE THREAD

**Issue by eriknelson** [konveyor/github-actions#13]
I want to be auto added to the "watcher" list on a Jira so that I get email
notifications from the Jira ticket that gets created. Hopefully the Jira
API allows for this in some manner.

**Comment by djzager** [comment]
A few things:
1. You can't add watchers at issue creation time. Must create issue, then add watcher(s).
2. Appears you have to add watchers 1 at a time through the API
3. Appears idempotent, if I make the same request (example below) multiple times, it doesn't add the user multiple times. 

To add one person as a watcher to an issue, in curl this would look like:

```
curl -k \
--request POST \
--header "Authorization: Bearer ${TOKEN}" \
--header "Content-Type: application/json" \
--header "Accept-Type: application/json" \
--data '"${USER_EMAIL}"' \
https://issues.redhat.com/rest/api/2/issue/${ISSUE_ID}/watchers
```

My thought on how this would be implemented would be to expose an `addWatchers` input to the reconcile-issue action that accepted a comma separated list. And for each user, we would add them to the watchers of the issue synced to Jira.

**Comment by djzager** [comment]
Since I'm not actively working on this one. I'm going to drop myself from assignee.

**Comment by eriknelson** [comment]
Also going to pick this one up

**Comment by eriknelson** [comment]
That took me a lot longer to figure out than it should have, I thought the body was JSON but it's literally a raw string with the user email. Now that I know what the API looks like and I've got an environment I can make changes within, I should be able to post a PR for this.
