### ISSUE TITLE
Untriaged notifications

### ISSUE THREAD

**Issue by eriknelson** [konveyor/github-actions#8]
We need to add a nightly job (perhaps a GH action) that can be a designated
place for tasks that generally don't aren't run on the normal GH event trigger.

Primarily, we need a notification service that runs daily and posts a list
of all `needs-triage` issues to a Slack channel. We should write this so that
it's easy to swap out the destination of where this "needs triage" report goes,
because this list could grow to be quite large, and/or we might want to send
it in an email to a list or individuals.

I'm conflating two things, but it might also be nice to run general cleanup
tasks here such as enforcing valid states and alerting to issues that we find,
such as an issue that has no release, is triaged/accepted, but does not have
a priority.

**Comment by eriknelson** [comment]
@djzager I think thsi might be done?

**Comment by djzager** [comment]
https://github.com/konveyor/github-actions/pull/12
